# -*- coding: utf-8 -*-
"""「ML期末 執行.ipynb」的副本

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YK4QgdMI3U74nEfE-xq6mpdCUJq2Id_j
"""

import os
import zipfile
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm
from collections import defaultdict
import warnings

warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', category=pd.errors.PerformanceWarning)


#1.資料夾路徑
real_futures_dir = "/content/drive/MyDrive/binance_backup/binance_5m_zips"

if not os.path.exists(real_futures_dir):
    raise FileNotFoundError(f"找不到路徑")

all_zip_files = [f for f in os.listdir(real_futures_dir) if f.endswith('.zip')]
print(f"共有{len(all_zip_files)}個壓縮")

#2.同幣種所有月份檔案歸類

symbol_files_map = defaultdict(list)
for f_file in all_zip_files:
    symbol = f_file.split('-')[0]
    symbol_files_map[symbol].append(f_file)

print(f"共{len(symbol_files_map)}檔永續合約標的")


#3.跨月份黏合與8H降頻

symbol_close_dict = {}

for symbol, month_files in tqdm(symbol_files_map.items(), desc="跨月份黏合並聚合8H價格"):
    symbol_all_months_dfs = []

    #遍歷該幣種的所有歷史月份檔案
    for month_file in month_files:
        file_path = os.path.join(real_futures_dir, month_file)
        try:
            with zipfile.ZipFile(file_path, 'r') as z:
                csv_inside = [f for f in z.namelist() if f.endswith('.csv')][0]

                #僅讀取時間戳與收盤價
                df_month = pd.read_csv(z.open(csv_inside), header=None, usecols=[0, 4])
                df_month.columns = ['timestamp', 'f_close']

                #排除可能混入的header文字
                df_month = df_month[df_month['timestamp'] != 'open_time']

                symbol_all_months_dfs.append(df_month)
        except Exception as e:

            pass

    if not symbol_all_months_dfs:
        continue

    # 垂直黏合該幣種所有月份
    df_total = pd.concat(symbol_all_months_dfs, ignore_index=True)

    #資料型態轉換與清洗
    df_total['timestamp'] = pd.to_datetime(pd.to_numeric(df_total['timestamp']), unit='ms', errors='coerce')
    df_total['f_close'] = pd.to_numeric(df_total['f_close'], errors='coerce')
    df_total = df_total.dropna().set_index('timestamp').sort_index()

    #剔除可能重複的時間戳紀錄
    df_total = df_total_cleaned = df_total[~df_total.index.duplicated(keep='first')]

    #抓取 00:00, 08:00, 16:00的最後價格
    df_8h = df_total['f_close'].resample('8H').last()

    symbol_close_dict[symbol] = df_8h


#4.橫截面矩陣與未來報酬率Y計算

#全市場二維價格寬表
futures_price_matrix = pd.DataFrame(symbol_close_dict).ffill().fillna(0)

#預測目標Y
futures_return_matrix = futures_price_matrix.pct_change(periods=1).shift(-1)


# 5.品質驗收

print(f"歷史價格表維度:{futures_price_matrix.shape}")
print(f"預測標籤Y維度:{futures_return_matrix.shape}")

if futures_return_matrix.shape[0] > 0:
    print(f"歷史時間軸起點:{futures_return_matrix.index.min()}")
    print(f"歷史時間軸終點:{futures_return_matrix.index.max()}")
    print("\n預期合約報酬率Y表前5行預覽：")
    print(futures_return_matrix.head())
else:
    print("矩陣為空")

import os
import json
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', category=pd.errors.PerformanceWarning)

#1.設定路徑與定義6大特徵
feature_dir = "./alpha_features"

factor_files = {
    'feat_basis_abs': '/content/drive/MyDrive/basis_absolute.csv',
    'feat_basis_speed': '/content/drive/MyDrive/basis_speed.csv',
    'feat_basis_vol': '/content/drive/MyDrive/basis_micro_vol.csv',
    'feat_price_corr': '/content/drive/MyDrive/price_micro_corr.csv',
    'feat_basis_zscore': '/content/drive/MyDrive/basis_zscore_7d.csv',
    'feat_illiquidity': '/content/drive/MyDrive/futures_illiquidity.csv'
}

stacked_series = {}

#2.遍歷6張橫截面寬表進行空間壓縮
for feat_name, file_name in factor_files.items():
    file_path = file_name if file_name.startswith('/') else os.path.join(feature_dir, file_name)

    if not os.path.exists(file_path):
        raise FileNotFoundError(f"找不到特徵檔案")
    df_matrix = pd.read_csv(file_path, index_col='timestamp', parse_dates=True

    stacked_series[feat_name] = df_matrix.stack()

#合成初步DataFrame
ml_panel_df = pd.DataFrame(stacked_series)
ml_panel_df.index.names = ['timestamp', 'symbol']

print(f"初步長表維度:{ml_panel_df.shape}")


#3.ML預測目標Y
# ==============================================================================

y_file_path = '/content/drive/MyDrive/futures_return_matrix_8h.csv'
if not os.path.exists(y_file_path):
    raise FileNotFoundError(f"找不到報酬率Y檔案")

#讀取報酬率寬表矩陣
y_matrix = pd.read_csv(y_file_path, index_col='timestamp', parse_dates=True)

ml_panel_df['target_y'] = y_matrix.stack()


#4.剔除新幣未上線樣本與殘缺值

ml_panel_df = ml_panel_df[ml_panel_df['feat_basis_abs'] != 0]
ml_panel_df = ml_panel_df.dropna(subset=['target_y'])


#5.載入Universe滾動JSON檔
# ==============================================================================
json_path = '/content/drive/MyDrive/universe_history.json'
if not os.path.exists(json_path):
    raise FileNotFoundError(f"找不到")

with open(json_path, 'r') as f:
    universe_history = json.load(f)

print(f"面板數據維度:{ml_panel_df.shape}")
print(f"總計覆蓋的時間節點數:{len(ml_panel_df.index.get_level_values('timestamp').unique())}個8H區間")
print(f"有效標的數: {len(ml_panel_df.index.get_level_values('symbol').unique())}檔幣")
print("\n前5行長相預覽：")
print(ml_panel_df.head())

import os
import json
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge
import lightgbm as lgb
from tqdm.notebook import tqdm
import warnings

warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', category=pd.errors.PerformanceWarning)

#1.載入
feature_dir = "./alpha_features"
factor_files = {
    'feat_basis_abs': '/content/drive/MyDrive/basis_absolute.csv',
    'feat_basis_speed': '/content/drive/MyDrive/basis_speed.csv',
    'feat_basis_vol': '/content/drive/MyDrive/basis_micro_vol.csv',
    'feat_price_corr': '/content/drive/MyDrive/price_micro_corr.csv',
    'feat_basis_zscore': '/content/drive/MyDrive/basis_zscore_7d.csv',
    'feat_illiquidity': '/content/drive/MyDrive/futures_illiquidity.csv'
}

stacked_series = {}
for feat_name, file_name in factor_files.items():
    file_path = file_name if file_name.startswith('/') else os.path.join(feature_dir, file_name)

    if not os.path.exists(file_path):
        raise FileNotFoundError(f"找不到")
    df_temp = pd.read_csv(file_path, index_col='timestamp', parse_dates=True)
    stacked_series[feat_name] = df_temp.stack()

#轉換成DataFrame
ml_panel_df = pd.DataFrame(stacked_series)
ml_panel_df.index.names = ['timestamp', 'symbol']

#核心黏合
y_file_path = '/content/drive/MyDrive/futures_return_matrix_8h.csv'
if not os.path.exists(y_file_path):
    raise FileNotFoundError(f"找不到")
futures_return_matrix = pd.read_csv(y_file_path, index_col='timestamp', parse_dates=True)

ml_panel_df['target_y'] = futures_return_matrix.stack()

#清洗殘缺值與未上線樣本
ml_panel_df = ml_panel_df.dropna(subset=['target_y'])
ml_panel_df = ml_panel_df[ml_panel_df['feat_basis_abs'] != 0]


#2.橫截面標準化優化
feature_cols = list(factor_files.keys())

ml_panel_scaled = ml_panel_df.copy()
ml_panel_scaled[feature_cols] = ml_panel_df.groupby('timestamp', group_keys=False).apply(
    lambda x: (x[feature_cols] - x[feature_cols].mean()) / x[feature_cols].std().replace(0, 1.0).fillna(1.0)
)

#讀取動態Universe
with open('/content/drive/MyDrive/universe_history.json', 'r') as f:
    universe_history = json.load(f)


#3.初始化Walk-Forward時序表與紀錄容器

timestamps = ml_panel_scaled.index.get_level_values('timestamp').unique().sort_values()
all_symbols = ml_panel_scaled.index.get_level_values('symbol').unique()

#建立預測儲存矩陣
pred_linear_matrix = pd.DataFrame(np.nan, index=timestamps, columns=all_symbols)
pred_nonlinear_matrix = pd.DataFrame(np.nan, index=timestamps, columns=all_symbols)

#儲存歷史軌跡
hyperparam_history = []
linear_coef_history = []
nonlinear_importance_history = []

#網格候選
ridge_alphas = [0.01, 0.1, 1.0, 10.0, 100.0]
lgb_depths = [4]
lgb_leaves = [4, 8, 12, 16]

#滾動起迄點
start_idx = 1643
end_idx = len(timestamps)

print(f"\n預報窗口:第{start_idx}期->第{end_idx}期")


#4.ExpandingWindow迴圈

for idx in tqdm(range(start_idx, end_idx), desc="預報中"):
    current_t = timestamps[idx]

    # 判定當期Universe標的名單
    current_week_str = current_t.strftime('%Y-W%W')
    if current_week_str not in universe_history:
        avail_weeks = [w for w in universe_history.keys() if w <= current_week_str]
        current_week_str = avail_weeks[-1] if avail_weeks else list(universe_history.keys())[0]
    top_20_symbols = universe_history[current_week_str]

    #擷取截至t-1，並過濾當期Universe
    history_ts = timestamps[:idx]
    hist_data_scaled = ml_panel_scaled.loc[history_ts]
    hist_data_scaled = hist_data_scaled[hist_data_scaled.index.get_level_values('symbol').isin(top_20_symbols)].dropna()

    if hist_data_scaled.empty or len(hist_data_scaled.index.get_level_values('timestamp').unique()) < 10:
        continue

    #動態等比例切分
    unique_hist_times = hist_data_scaled.index.get_level_values('timestamp').unique().sort_values()
    split_point = int(len(unique_hist_times) * (2/3))

    train_df = hist_data_scaled.loc[unique_hist_times[:split_point]]
    val_df = hist_data_scaled.loc[unique_hist_times[split_point:]]

    X_train, y_train = train_df[feature_cols], train_df['target_y']
    X_val, y_val = val_df[feature_cols], val_df['target_y']

    #Ridge調優Lambda
    best_alpha, best_lin_mse = 1.0, float('inf')
    for alpha_cand in ridge_alphas:
        model_lin = Ridge(alpha=alpha_cand, random_state=42)
        model_lin.fit(X_train, y_train)
        mse = np.mean((y_val - model_lin.predict(X_val)) ** 2)
        if mse < best_lin_mse:
            best_lin_mse = mse
            best_alpha = alpha_cand

    #歷史合體擬合
    final_lin = Ridge(alpha=best_alpha, random_state=42)
    final_lin.fit(hist_data_scaled[feature_cols], hist_data_scaled['target_y'])


    #LightGBM深度與葉子網格搜尋
    best_leaves, best_depth, best_lgb_mse = 15, 4, float('inf')
    for depth_cand in lgb_depths:
        for leaves_cand in lgb_leaves:
            if leaves_cand >= (2 ** depth_cand):
                continue

            model_lgb = lgb.LGBMRegressor(num_leaves=leaves_cand, max_depth=depth_cand, learning_rate=0.05,
                                          n_estimators=30, random_state=42, verbose=-1)
            model_lgb.fit(X_train, y_train)
            mse = np.mean((y_val - model_lgb.predict(X_val)) ** 2)
            if mse < best_lgb_mse:
                best_lgb_mse = mse
                best_leaves = leaves_cand
                best_depth = depth_cand

    #全歷史合體擬合
    final_lgb = lgb.LGBMRegressor(num_leaves=best_leaves, max_depth=best_depth, learning_rate=0.05,
                                  n_estimators=30, random_state=42, verbose=-1)
    final_lgb.fit(hist_data_scaled[feature_cols], hist_data_scaled['target_y'])


    #歷史軌跡快照
    hyperparam_history.append({
        'timestamp': current_t,
        'best_lambda': best_alpha,
        'best_leaves': best_leaves,
        'best_depth': best_depth
    })
    linear_coef_history.append(np.append([current_t], final_lin.coef_))
    nonlinear_importance_history.append(np.append([current_t], final_lgb.feature_importances_))


    # 4g.當前第t期外推預測
    current_sample_scaled = ml_panel_scaled.loc[[current_t]]
    current_sample_scaled = current_sample_scaled[current_sample_scaled.index.get_level_values('symbol').isin(top_20_symbols)]

    if not current_sample_scaled.empty:
        X_test = current_sample_scaled[feature_cols]
        target_symbols = current_sample_scaled.index.get_level_values('symbol')

        #輸出模型對未來8H合約實現報酬率的預測值，填表
        pred_linear_matrix.loc[current_t, target_symbols] = final_lin.predict(X_test)
        pred_nonlinear_matrix.loc[current_t, target_symbols] = final_lgb.predict(X_test)


print(f"線性預測矩陣有效區間維度: {pred_linear_matrix.loc[timestamps[start_idx]:timestamps[end_idx-1]].dropna(how='all').shape}")
print(f"非線性預測矩陣有效區間維度: {pred_nonlinear_matrix.loc[timestamps[start_idx]:timestamps[end_idx-1]].dropna(how='all').shape}")

import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore', category=FutureWarning)


#1.檢查
if 'pred_linear_matrix' not in globals() or 'pred_nonlinear_matrix' not in globals():
    raise NameError("錯誤")
if 'futures_return_matrix' not in globals():
    raise NameError("錯誤")

#鎖定測試集時間軸
test_timestamps = pred_linear_matrix.dropna(how='all').index.sort_values()


#2.定義橫截面四等分組回測
def backtest_model_predictions(pred_matrix, real_return_matrix, timestamps):
    #來記錄各組每期真實回報
    d1_returns, d2_returns, d3_returns, d4_returns = [], [], [], []

    for t in timestamps:
        #抓出當期20檔幣的預測得分與真實報酬率
        t_preds = pred_matrix.loc[t].dropna()
        t_real_rets = real_return_matrix.loc[t]

        if t_preds.empty:
            continue

        #橫截面排序
        sorted_symbols = t_preds.sort_values(ascending=False).index.tolist()
        n_symbols = len(sorted_symbols)

        #四等分
        q = n_symbols // 4
        group_d1 = sorted_symbols[:q]
        group_d2 = sorted_symbols[q:2*q]
        group_d3 = sorted_symbols[2*q:3*q]
        group_d4 = sorted_symbols[3*q:]

        #真實回報下一期的真正損益，計算等權重平均數
        d1_returns.append(t_real_rets.loc[group_d1].mean())
        d2_returns.append(t_real_rets.loc[group_d2].mean())
        d3_returns.append(t_real_rets.loc[group_d3].mean())
        d4_returns.append(t_real_rets.loc[group_d4].mean())

    #整合時序DataFrame
    pnl_df = pd.DataFrame({
        'D1_Return': d1_returns,
        'D2_Return': d2_returns,
        'D3_Return': d3_returns,
        'D4_Return': d4_returns
    }, index=timestamps)

    #多空對沖組合損益
    pnl_df['Long_Short_Return'] = pnl_df['D1_Return'] - pnl_df['D4_Return']

    #計算累積收益率
    pnl_df['Cum_D1'] = (1 + pnl_df['D1_Return']).cumprod() - 1
    pnl_df['Cum_D2'] = (1 + pnl_df['D2_Return']).cumprod() - 1
    pnl_df['Cum_D3'] = (1 + pnl_df['D3_Return']).cumprod() - 1
    pnl_df['Cum_D4'] = (1 + pnl_df['D4_Return']).cumprod() - 1
    pnl_df['Cum_Long_Short'] = (1 + pnl_df['Long_Short_Return']).cumprod() - 1

    return pnl_df


#3雙線路並行回測
print("Ridge橫截面分組回測")
linear_pnl_results = backtest_model_predictions(pred_linear_matrix, futures_return_matrix, test_timestamps)

print("LightGBM橫截面分組回測")
nonlinear_pnl_results = backtest_model_predictions(pred_nonlinear_matrix, futures_return_matrix, test_timestamps)


#4.初步成果驗收驗證


print(f"線性回測損益表維度:{linear_pnl_results.shape}")
print(f"非線性回測損益表維度:{nonlinear_pnl_results.shape}")
print("\n非線性模型的分組回測收益率預覽：")
print(nonlinear_pnl_results[['D1_Return', 'D4_Return', 'Long_Short_Return']].head())

import os
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import numpy as np
import pandas as pd
import warnings
import logging

warnings.filterwarnings('ignore')
logging.getLogger('lightgbm').setLevel(logging.ERROR)


#中文字型檔
font_url = "https://github.com/googlefonts/noto-cjk/raw/main/Sans/OTC/NotoSansCJK-Regular.ttc"
font_path = "NotoSansCJK-Regular.ttc"

if not os.path.exists(font_path):
    import urllib.request
    urllib.request.urlretrieve(font_url, font_path)

fe = fm.FontEntry(fname=font_path, name='NotoSansCJK')
fm.fontManager.ttflist.insert(0, fe)
plt.rcParams['font.family'] = ['NotoSansCJK']
plt.rcParams['axes.unicode_minus'] = False

#1.績效指標計算函數

def calculate_performance_metrics(pnl_df):
    metrics = {}
    ann_factor = 1095

    for col in ['D1_Return', 'D2_Return', 'D3_Return', 'D4_Return', 'Long_Short_Return']:
        group_name = col.replace('_Return', '')
        rets = pnl_df[col]


        cum_wealth = (1 + rets).cumprod()
        total_wealth_multiple = cum_wealth.iloc[-1]

        ann_ret_geo = (total_wealth_multiple) ** (ann_factor / len(rets)) - 1

        ann_vol = rets.std() * np.sqrt(ann_factor)
        ir = ann_ret_geo / ann_vol if ann_vol != 0 else 0
        win_rate = (rets > 0).sum() / len(rets)

        #動態最大回撤
        running_max = cum_wealth.cummax()
        drawdown = (cum_wealth - running_max) / running_max
        max_dd = drawdown.min()

        metrics[group_name] = {
            '年化收益率': f"{ann_ret_geo:.2%}",
            '年化波動度': f"{ann_vol:.2%}",
            '資訊比率(IR)': f"{ir:.4f}",
            '單期勝率': f"{win_rate:.2%}",
            '最大回撤(MDD)': f"{max_dd:.2%}"
        }
    return pd.DataFrame(metrics).T

def print_perfect_aligned_table(title, df):
    print(f"\n========================================================")
    print(f"{title}各組別與多空對沖組合績效指標（幾何年化）：")
    print("==========================================================")

    header = f"{'組別':<18}" + "".join([f"{col:>15}" for col in df.columns])
    print(header)
    print("-" * len(header) * 1)

    for idx, row in df.iterrows():
        row_str = f"{idx:<18}" + "".join([f"{row[col]:>17}" for col in df.columns])
        print(row_str)
    print("==========================================================")

# 執行指標計算
linear_metrics_table = calculate_performance_metrics(linear_pnl_results)
nonlinear_metrics_table = calculate_performance_metrics(nonlinear_pnl_results)

# 使用全新幾何美化函數列印
print_perfect_aligned_table("Ridge", linear_metrics_table)
print_perfect_aligned_table("LightGBM", nonlinear_metrics_table)


#2.Long-Short淨值對比圖
plt.figure(figsize=(14, 6.5), dpi=150)
plt.plot(linear_pnl_results['Cum_Long_Short'], label='Ridge淨值曲線', color='#2ca02c', linewidth=2)
plt.plot(nonlinear_pnl_results['Cum_Long_Short'], label='LightGBM淨值曲線', color='#ff7f0e', linewidth=2.5)

plt.title('線性與非線性永續合約多空對沖策略累積收益率對比', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('回測時序', fontsize=11)
plt.ylabel('累積收益率', fontsize=11)
plt.gca().yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: '{:.0%}'.format(y)))
plt.legend(loc='upper left', fontsize=11, frameon=True, shadow=True)
plt.tight_layout()
plt.savefig('long_short_comparison.png')
plt.show()


#3.四等分組單邊淨值單調性檢驗圖
plt.figure(figsize=(14, 6.5), dpi=150)
plt.plot(nonlinear_pnl_results['Cum_D1'], label='D1 (預期最強組 - 做多標的池)', color='#d62728', linewidth=1.8)
plt.plot(nonlinear_pnl_results['Cum_D2'], label='D2 (次強組)', color='#1f77b4', linewidth=1.5, linestyle='--')
plt.plot(nonlinear_pnl_results['Cum_D3'], label='D3 (次弱組)', color='#bcbd22', linewidth=1.5, linestyle='--')
plt.plot(nonlinear_pnl_results['Cum_D4'], label='D4 (預期最弱組 - 做空標的池)', color='#7f7f7f', linewidth=1.8)

plt.title('非線性模型單調性檢驗', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('回測時序', fontsize=11)
plt.ylabel('累積收益率', fontsize=11)
plt.gca().yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: '{:.0%}'.format(y)))
plt.legend(loc='upper left', fontsize=11, frameon=True, shadow=True)
plt.tight_layout()
plt.savefig('monotonicity_check_lgbm.png')
plt.show()


#4.四等分組單邊淨值單調性檢驗圖
plt.figure(figsize=(14, 6.5), dpi=150)
plt.plot(linear_pnl_results['Cum_D1'], label='D1 (預期最強組 - 做多標的池)', color='#d62728', linewidth=1.8)
plt.plot(linear_pnl_results['Cum_D2'], label='D2 (次強組)', color='#1f77b4', linewidth=1.5, linestyle='--')
plt.plot(linear_pnl_results['Cum_D3'], label='D3 (次弱組)', color='#bcbd22', linewidth=1.5, linestyle='--')
plt.plot(linear_pnl_results['Cum_D4'], label='D4 (預期最弱組 - 做空標的池)', color='#7f7f7f', linewidth=1.8)

plt.title('線性模型單調性檢驗', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('回測時序', fontsize=11)
plt.ylabel('累積收益率', fontsize=11)
plt.gca().yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: '{:.0%}'.format(y)))
plt.legend(loc='upper left', fontsize=11, frameon=True, shadow=True)
plt.tight_layout()
plt.savefig('monotonicity_check_ridge.png')
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import warnings

warnings.filterwarnings('ignore')


#思源黑體
font_path = "NotoSansCJK-Regular.ttc"
if os.path.exists(font_path):
    fe = fm.FontEntry(fname=font_path, name='NotoSansCJK')
    fm.fontManager.ttflist.insert(0, fe)
    plt.rcParams['font.family'] = ['NotoSansCJK']
plt.rcParams['axes.unicode_minus'] = False

feature_cols = ['絕對基差', '基差速度', '微觀波動度', '微觀相關性', '7D基差ZScore', '合約非流動性']
feature_eng_names = ['feat_basis_abs', 'feat_basis_speed', 'feat_basis_vol', 'feat_price_corr', 'feat_basis_zscore', 'feat_illiquidity']

#1.處理Ridge迴歸係數時序演變
coef_df = pd.DataFrame(linear_coef_history)
coef_df.columns = ['timestamp'] + feature_eng_names
coef_df = coef_df.set_index('timestamp').sort_index()

#絕對貢獻度，係數取絕對值，計算橫截面佔比
coef_abs = coef_df.abs()
coef_percentage = coef_abs.div(coef_abs.sum(axis=1), axis=0)
coef_percentage.columns = feature_cols


#2.LightGBM分裂增益重要性時序演變
importance_df = pd.DataFrame(nonlinear_importance_history)
importance_df.columns = ['timestamp'] + feature_eng_names
importance_df = importance_df.set_index('timestamp').sort_index()

#歸一化
importance_percentage = importance_df.div(importance_df.sum(axis=1), axis=0).fillna(0)
importance_percentage.columns = feature_cols


# 3.Ridge迴歸係數動態演變

fig, ax = plt.subplots(figsize=(14, 6), dpi=150)
ax.stackplot(coef_percentage.index, coef_percentage.T, labels=feature_cols,
             colors=['#1f77b4', '#aec7e8', '#ff7f0e', '#ffbb78', '#2ca02c', '#98df8a'], alpha=0.85)
ax.set_title(' ', fontsize=13, fontweight='bold', pad=12)
ax.set_ylabel('因子相對貢獻度佔比', fontsize=11)
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: '{:.0%}'.format(y)))
ax.set_ylim(0, 1)
ax.legend(loc='lower left', bbox_to_anchor=(0, 1.02, 1, 0.1), mode="expand", borderaxespad=0, ncol=6, fontsize=10, frameon=True)
plt.tight_layout()
plt.savefig('ridge_factor_evolution.png')
plt.show()


# 4.LightGBM因子增益重要性動態演變
fig, ax = plt.subplots(figsize=(14, 6), dpi=150)
ax.stackplot(importance_percentage.index, importance_percentage.T, labels=feature_cols,
             colors=['#1f77b4', '#aec7e8', '#ff7f0e', '#ffbb78', '#2ca02c', '#98df8a'], alpha=0.85)
ax.set_title(' ', fontsize=13, fontweight='bold', pad=12)
ax.set_ylabel('因子相對重要性佔比', fontsize=11)
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: '{:.0%}'.format(y)))
ax.set_ylim(0, 1)
ax.legend(loc='lower left', bbox_to_anchor=(0, 1.02, 1, 0.1), mode="expand", borderaxespad=0, ncol=6, fontsize=10, frameon=True)
plt.tight_layout()
plt.savefig('lgbm_factor_evolution.png')
plt.show()


#5.最優超參數統計特徵

param_df = pd.DataFrame(hyperparam_history)
print("\n========================================================")
print("最優超參數時序分佈統計：")
print("==========================================================")
print(f"Ridge best_lambda 出現頻率：")
print(param_df['best_lambda'].value_counts(normalize=True).map(lambda x: f"{x:.2%}"))
print(f"\nLightGBM best_leaves 出現頻率：")
print(param_df['best_leaves'].value_counts(normalize=True).map(lambda x: f"{x:.2%}"))

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import os


font_path = "NotoSansCJK-Regular.ttc"
if os.path.exists(font_path):
    fe = fm.FontEntry(fname=font_path, name='NotoSansCJK')
    fm.fontManager.ttflist.insert(0, fe)
    plt.rcParams['font.family'] = ['NotoSansCJK']
plt.rcParams['axes.unicode_minus'] = False

#1.資料整理
if 'hyperparam_history' not in globals() or len(hyperparam_history) == 0:
    raise NameError("❌ 錯誤：找不到超參數歷史紀錄，請確認第二部分的滾動調優大迴圈已成功執行。")

param_df = pd.DataFrame(hyperparam_history)
param_df = param_df.set_index('timestamp').sort_index()


#2.繪製雙子圖折線圖
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 8), sharex=True, dpi=150)

# --- 上圖：Ridge Lambda 軌跡 ---
ax1.plot(param_df.index, param_df['best_lambda'], color='#1f77b4', linewidth=1.5, drawstyle='steps-post', label='最佳 Lambda')
ax1.set_yscale('log')
ax1.set_yticks([0.01, 0.1, 1.0, 10.0, 100.0])
ax1.set_yticklabels(['0.01', '0.1', '1.0', '10.0', '100.0']) # Added '0.01' to match yticks
ax1.set_title('Ridge Best lambda時序演進軌跡', fontsize=12, fontweight='bold')
ax1.set_ylabel('正則化強度', fontsize=10)
ax1.grid(True, which="both", ls="--", alpha=0.5)
ax1.legend(loc='upper left', frameon=True)

# --- 下圖：LightGBM Leaves 軌跡 ---
ax2.plot(param_df.index, param_df['best_leaves'], color='#e377c2', linewidth=1.5, drawstyle='steps-post', label='最佳葉子節點數')
ax2.set_yticks([4, 8, 12, 16])
ax2.set_title('(LightGBM Best num_leaves 時序演進軌跡', fontsize=12, fontweight='bold')
ax2.set_xlabel('回測時序)', fontsize=11)
ax2.set_ylabel('葉子節點數', fontsize=10)
ax2.grid(True, ls="--", alpha=0.5)
ax2.legend(loc='upper left', frameon=True)

plt.tight_layout()
plt.savefig('hyperparam_evolution_lines.png')

import pandas as pd
import numpy as np
import scipy.stats as stats
import warnings

warnings.filterwarnings('ignore')


#1.載入整理歷史Ridge係數路徑

if 'linear_coef_history' not in globals() or len(linear_coef_history) == 0:
    raise NameError("錯誤")

feature_cols = ['絕對基差', '基差速度', '微觀波動度', '微觀相關性', '7D基差ZScore', '合約非流動性']
feature_eng_names = ['feat_basis_abs', 'feat_basis_speed', 'feat_basis_vol', 'feat_price_corr', 'feat_basis_zscore', 'feat_illiquidity']

# 轉換成DataFrame
coef_series_df = pd.DataFrame(linear_coef_history)
coef_series_df.columns = ['timestamp'] + feature_eng_names
coef_series_df = coef_series_df.set_index('timestamp').sort_index()


# 2.係數穩健性統計
ml_summary = pd.DataFrame(index=feature_cols)
ml_summary['歷史平均係數 (Mean_beta)'] = coef_series_df.mean().values
ml_summary['係數標準差 (Std_beta)'] = coef_series_df.std().values

#計算符號一致性 係數與平均值同號的時間佔比
ml_summary['符號一致性比率'] = [
    np.mean(np.sign(coef_series_df[col]) == np.sign(coef_series_df[col].mean()))
    for col in feature_eng_names
]
ml_summary['符號一致性比率'] = ml_summary['符號一致性比率'].map(lambda x: f"{x:.2%}")

# 3.Fama-MacBeth 顯著性檢定

t_stats = []
p_values = []

for col in feature_eng_names:
    series = coef_series_df[col].dropna()
    t_val, p_val = stats.ttest_1samp(series, 0)
    t_stats.append(t_val)
    p_values.append(p_val)

ml_summary['Fama-MacBeth_t-stat'] = t_stats
ml_summary['p-value'] = p_values
ml_summary['統計顯著性 (95% 水準)'] = ml_summary['p-value'].map(lambda x: '顯著' if x < 0.05 else '不顯著')

#格式化輸出
ml_summary['歷史平均係數 (Mean_beta)'] = ml_summary['歷史平均係數 (Mean_beta)'].map(lambda x: f"{x:.6f}")
ml_summary['係數標準差 (Std_beta)'] = ml_summary['係數標準差 (Std_beta)'].map(lambda x: f"{x:.6f}")
ml_summary['p-value'] = ml_summary['p-value'].map(lambda x: f"{x:.4e}" if x < 0.0001 else f"{x:.4f}")
ml_summary['Fama-MacBeth_t-stat'] = ml_summary['Fama-MacBeth_t-stat'].map(lambda x: f"{x:.4f}")


#4.成果
print("======================================================================")
print("Ridge 因子歷史係數與 Fama-MacBeth 顯著性檢定綜合表：")
print("==========================================================================")
print(ml_summary)