# -*- coding: utf-8 -*-
"""ML期末抓資料

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nel9WaiVGRLGs41DIfQEq6YPQTt-Z8Z0
"""

import os
import requests
import zipfile
import io
import pandas as pd
import json
from datetime import datetime, timedelta
from concurrent.futures import ThreadPoolExecutor
from tqdm.notebook import tqdm


#1.基礎參數設定與黑名單定義

start_year, end_year = 2023, 2025
download_dir = "./binance_daily_zip"
os.makedirs(download_dir, exist_ok=True)

HARD_BLACKLIST = {
    'USDT', 'USDC', 'DAI', 'USDe', 'FDUSD', 'PYUSD', 'TUSD', 'BUSD',
    'WBTC', 'STETH', 'WSTETH', 'CBETH', 'EETH', 'PUFETH', 'WBETH',
    'LEO', 'OKB', 'KCS', 'HTX', 'GT', 'PAXG', 'XAUT', 'ONDO', 'W', 'AXL'
}
FUZZY_BLACKLIST = ['USD', 'EUR', 'GOLD', 'WRAP', 'BOND']


#2.單線程獲取交易對

exchange_info_url = "https://fapi.binance.com/fapi/v1/exchangeInfo"
response = requests.get(exchange_info_url).json()

all_usdt_symbols = []

if 'symbols' not in response:
    print("錯誤")
else:
    all_usdt_symbols = [
        market['symbol'] for market in response['symbols']
        if market['quoteAsset'] == 'USDT' and market['contractType'] == 'PERPETUAL' and market['status'] == 'TRADING'
    ]

valid_symbols = []
for symbol in all_usdt_symbols:
    base_asset = symbol.replace('USDT', '')
    if base_asset in HARD_BLACKLIST or any(kw in base_asset for kw in FUZZY_BLACKLIST):
        continue
    valid_symbols.append(symbol)

print(f"實際需要調研:{len(valid_symbols)}檔幣。")


#3.生成全量任務行事曆

tasks = []
if valid_symbols: # Only generate tasks if there are valid symbols
    for symbol in valid_symbols:
        for year in range(start_year, end_year + 1):
            for month in range(1, 13):
                file_name = f"{symbol}-1d-{year}-{str(month).zfill(2)}"
                url = f"https://data.binance.vision/data/futures/um/monthly/klines/{symbol}/1d/{file_name}.zip"
                tasks.append((symbol, file_name, url))


#4.清洗函數

def fetch_and_clean(task):
    symbol, file_name, url = task
    try:
        res = requests.get(url, timeout=5)
        if res.status_code == 200:
            with zipfile.ZipFile(io.BytesIO(res.content)) as z:
                csv_name = f"{file_name}.csv"
                if csv_name in z.namelist():
                    df = pd.read_csv(z.open(csv_name), header=None)
                    df = df[df[0] != 'open_time']
                    df = df[[0, 1, 4, 5]]
                    df.columns = ['timestamp', 'open', 'close', 'volume']

                    df['timestamp'] = pd.to_numeric(df['timestamp'], errors='coerce')
                    df['open'] = pd.to_numeric(df['open'], errors='coerce')
                    df['close'] = pd.to_numeric(df['close'], errors='coerce')
                    df['volume'] = pd.to_numeric(df['volume'], errors='coerce')
                    df = df.dropna()

                    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
                    df['daily_turnover'] = ((df['open'] + df['close']) / 2) * df['volume']
                    df['symbol'] = symbol
                    return df[['timestamp', 'symbol', 'daily_turnover']]
    except:
        pass
    return None


#5.下載與清洗
# ==============================================================================
all_dfs = []

if tasks: # Only proceed if there are tasks to execute
    with ThreadPoolExecutor(max_workers=20) as executor:
        futures = [executor.submit(fetch_and_clean, task) for task in tasks]
        for future in tqdm(futures, desc="清洗中"):
            res_df = future.result()
            if res_df is not None and not res_df.empty:
                all_dfs.append(res_df)

if all_dfs: # Only concatenate if there are dataframes to concatenate
    full_daily_df = pd.concat(all_dfs, ignore_index=True)


    #6.每週滾動樣本池矩陣運算

    turnover_matrix = full_daily_df.pivot(index='timestamp', columns='symbol', values='daily_turnover').fillna(0)

    current_monday = turnover_matrix.index.min() + timedelta(days=(0 - turnover_matrix.index.min().weekday()) % 7)
    end_date = turnover_matrix.index.max()

    universe_history = {}
    global_universe_set = set()

    while current_monday <= end_date:
        if current_monday >= datetime(2026, 1, 1):
            break
        last_week_turnover = turnover_matrix.loc[current_monday - timedelta(days=7) : current_monday - timedelta(days=1)]
        if not last_week_turnover.empty:
            top_20 = last_week_turnover.mean(axis=0).sort_values(ascending=False).head(20).index.tolist()
            universe_history[current_monday.strftime('%Y-W%W')] = top_20
            global_universe_set.update(top_20)
        current_monday += timedelta(days=7)

    with open('universe_history.json', 'w') as f:
        json.dump(universe_history, f, indent=4)

    global_universe_list = list(global_universe_set)
    print(f"2. 總聯集池幣種數量:{len(global_universe_list)}")
    print(global_universe_list)
else: # Corrected from elso
    print("無符合過濾條件的交易對")
    # Create an empty universe_history.json if no data was processed to avoid FileNotFoundError in subsequent cells
    with open('universe_history.json', 'w') as f:
        json.dump({}, f, indent=4)

import os
import json
import requests
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm.notebook import tqdm

#1.建立5m高頻資料夾
save_dir = ".binance_futures_5m_zips"
os.makedirs(save_dir, exist_ok=True)

#讀取上階段的JSON檔
json_path = '/content/drive/MyDrive/universe_history.json'
if not os.path.exists(json_path):
    raise FileNotFoundError(f"❌ 找不到 {json_path}，請確認第一階段是否成功跑完並產出檔案。")

with open(json_path, 'r') as f:
    universe_history = json.load(f)

#提取出所有出現過的幣種
symbols = set()
for week, symbol_list in universe_history.items():
    symbols.update(symbol_list)
symbols = list(symbols)

print(f"Universe共包含{len(symbols)}檔幣")


#3.預先生成下載
download_tasks = []
for symbol in symbols:
    for year in [2023, 2024, 2025]:
        for month in range(1, 13):
            file_name = f"{symbol}-5m-{year}-{str(month).zfill(2)}.zip"
            url = f"https://data.binance.vision/data/futures/um/monthly/klines/{symbol}/5m/{file_name}"
            local_path = os.path.join(save_dir, file_name)
            download_tasks.append((url, local_path))

print(f"生成{len(download_tasks)}個下載任務")


#4.執行緒下載函數
def download_single_file(task):
    url, local_path = task
    if os.path.exists(local_path):
        return True
    try:
        res = requests.get(url, timeout=5)
        if res.status_code == 200:
            with open(local_path, "wb") as f:
                f.write(res.content)
            return True
    except:
        pass
    return False

#5.開跑
success_count = 0
with ThreadPoolExecutor(max_workers=20) as executor:
    futures = {executor.submit(download_single_file, task): task for task in download_tasks}
    for future in tqdm(as_completed(futures), total=len(futures), desc="下載中"):
        if future.result():
            success_count += 1

print(f"下載了{success_count}個數據")
print(f"存放在Colab虛擬機的`{save_dir}`")

import os
import json
import requests
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm.notebook import tqdm

#1.建立現貨5m雲端暫存資料夾
spot_dir = "/content/binance_spot_5m_zips"
os.makedirs(spot_dir, exist_ok=True)

json_path = '/content/drive/MyDrive/universe_history.json'
if not os.path.exists(json_path):
    raise FileNotFoundError(f"錯誤")

with open(json_path, 'r') as f:
    universe_history = json.load(f)

#聯集池幣種
symbols = set()
for week, symbol_list in universe_history.items():
    symbols.update(symbol_list)
symbols = list(symbols)

print(f"共包含{len(symbols)}檔幣種。")


#2.全量現貨下載
download_tasks = []
for symbol in symbols:
    for year in [2023, 2024, 2025]:
        for month in range(1, 13):
            file_name = f"{symbol}-5m-{year}-{str(month).zfill(2)}.zip"
            url = f"https://data.binance.vision/data/spot/monthly/klines/{symbol}/5m/{file_name}"
            local_path = os.path.join(spot_dir, file_name)
            download_tasks.append((url, local_path))

print(f"總生成{len(download_tasks)}個現貨5m數據")

# 3. 核心多執行緒下載函數
def download_spot_file(task):
    url, local_path = task
    if os.path.exists(local_path):
        return True
    try:

        res = requests.get(url, timeout=5)
        if res.status_code == 200:
            with open(local_path, "wb") as f:
                f.write(res.content)
            return True
        elif res.status_code == 404:
            return False
    except Exception:
        return False


#4.開跑

success_count = 0
with ThreadPoolExecutor(max_workers=20) as executor:

    futures = {executor.submit(download_spot_file, task): task for task in download_tasks}


    for future in tqdm(as_completed(futures), total=len(futures), desc="下載中"):
        if future.result():
            success_count += 1

print(f"下載了{success_count}個現貨")
print(f"檔案在Colab虛擬機的`{spot_dir}` 資料夾")

import os
import zipfile
import pandas as pd
import numpy as np
import warnings
from datetime import datetime, timedelta
from tqdm.notebook import tqdm
from collections import defaultdict

warnings.filterwarnings('ignore')


#1.初始化資料夾路徑
futures_dir = "/content/binance_futures_5m_zips"
spot_dir = "./binance_spot_5m_zips"
output_dir = "./alpha_features"
os.makedirs(output_dir, exist_ok=True)

#掃描期現所有ZIP
f_files = [f for f in os.listdir(futures_dir) if f.endswith('.zip')]
s_files = [f for f in os.listdir(spot_dir) if f.endswith('.zip')]

#幣種->月份檔案
futures_map = defaultdict(list)
for f in f_files:
    symbol = f.split('-')[0]
    futures_map[symbol].append(f)

sport_map = defaultdict(list)
for f in s_files:
    symbol = f.split('-')[0]
    sport_map[symbol].append(f)

#找出期貨與現貨同時存在的交集幣
valid_symbols = list(set(futures_map.keys()) & set(sport_map.keys()))
print(f"共{len(valid_symbols)}檔幣進入6大Alpha因子矩陣")


#2.5m微觀聚合->8H降頻
def process_symbol_features(symbol):
    #讀取並合併期貨3年5m數據
    f_month_dfs = []
    for f_file in futures_map[symbol]:
        try:
            with zipfile.ZipFile(os.path.join(futures_dir, f_file), 'r') as z:
                csv = f_file.replace('.zip', '.csv')
                df = pd.read_csv(z.open(csv), header=None, usecols=[0, 4, 5])
                df.columns = ['timestamp', 'f_close', 'f_volume']
                df = df[df['timestamp'] != 'open_time']
                f_month_dfs.append(df)
        except: pass

    #讀取並合併現貨3年5m數據
    s_month_dfs = []
    for s_file in sport_map[symbol]:
        try:
            with zipfile.ZipFile(os.path.join(spot_dir, s_file), 'r') as z:
                csv = s_file.replace('.zip', '.csv')
                df = pd.read_csv(z.open(csv), header=None, usecols=[0, 4])
                df.columns = ['timestamp', 's_close']
                df = df[df['timestamp'] != 'open_time']
                s_month_dfs.append(df)
        except: pass

    if not f_month_dfs or not s_month_dfs: return None

    f_df = pd.concat(f_month_dfs, ignore_index=True)
    s_df = pd.concat(s_month_dfs, ignore_index=True)

    for df_raw in [f_df, s_df]: # Renamed loop variable to avoid confusion
        for col in df_raw.columns:
            df_raw[col] = pd.to_numeric(df_raw[col], errors='coerce')

        df_raw['timestamp'] = pd.to_datetime(df_raw['timestamp'], unit='ms', errors='coerce')
        df_raw.dropna(subset=['timestamp'], inplace=True)

        df_raw = df_raw[(df_raw['timestamp'] >= '2023-01-01') & (df_raw['timestamp'] <= '2026-01-01')]

    f_df = f_df.set_index('timestamp').sort_index()
    s_df = s_df.set_index('timestamp').sort_index()


    merged_5m = pd.merge_asof(
        f_df.reset_index(),
        s_df.reset_index(),
        on='timestamp',
        direction='nearest',
        tolerance=pd.Timedelta('15s')
    ).set_index('timestamp')
    if merged_5m.empty: return None

    merged_5m['f_return'] = merged_5m['f_close'].pct_change().abs()
    merged_5m['basis_5m'] = (merged_5m['f_close'] - merged_5m['s_close']) / merged_5m['s_close']
    merged_5m['amihud_raw'] = np.where(merged_5m['f_volume'] > 0, merged_5m['f_return'] / merged_5m['f_volume'], 0)

    #降頻聚合
    resampled_8h = pd.DataFrame(index=merged_5m['f_close'].resample('8h').last().index)
    resampled_8h['f1_basis'] = merged_5m['basis_5m'].resample('8h').last()
    resampled_8h['f2_delta_basis'] = resampled_8h['f1_basis'].diff()
    resampled_8h['f3_basis_std'] = merged_5m['basis_5m'].resample('8h').std()

    def calc_corr(window):
        if len(window) < 10: return np.nan
        return window['f_close'].corr(window['s_close'])
    resampled_8h['f4_price_corr'] = merged_5m[['f_close', 's_close']].resample('8h').apply(calc_corr)
    resampled_8h['f6_illiquidity'] = merged_5m['amihud_raw'].resample('8h').mean()

    rolling_mean = resampled_8h['f1_basis'].rolling(window=21, min_periods=5).mean()
    rolling_std = resampled_8h['f1_basis'].rolling(window=21, min_periods=5).std()
    resampled_8h['f5_basis_zscore'] = np.where(rolling_std > 0, (resampled_8h['f1_basis'] - rolling_mean) / rolling_std, 0)

    resampled_8h = resampled_8h.ffill().fillna(0)
    resampled_8h['symbol'] = symbol
    return resampled_8h.reset_index()


# 3. 執行流式運算
all_symbol_features = []
for symbol in tqdm(valid_symbols, desc="洗煉中"):
    res = process_symbol_features(symbol)
    if res is not None:
        all_symbol_features.append(res)

full_feature_df = pd.concat(all_symbol_features, ignore_index=True)
full_feature_df = full_feature_df[(full_feature_df['timestamp'] >= '2023-01-01') & (full_feature_df['timestamp'] <= '2025-12-31')]

factor_names = {
    'f1_basis': 'basis_absolute.csv',
    'f2_delta_basis': 'basis_speed.csv',
    'f3_basis_std': 'basis_micro_vol.csv',
    'f4_price_corr': 'price_micro_corr.csv',
    'f5_basis_zscore': 'basis_zscore_7d.csv',
    'f6_illiquidity': 'futures_illiquidity.csv'
}

for field, file_name in factor_names.items():
    matrix = full_feature_df.pivot(index='timestamp', columns='symbol', values=field)
    matrix = matrix.ffill().fillna(0)
    matrix.to_csv(os.path.join(output_dir, file_name))
    print(f"因子矩陣表->{file_name}|維度:{matrix.shape}")