{
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import requests\n",
        "import zipfile\n",
        "import io\n",
        "import pandas as pd\n",
        "import json\n",
        "from datetime import datetime, timedelta\n",
        "from concurrent.futures import ThreadPoolExecutor\n",
        "from tqdm.notebook import tqdm\n",
        "\n",
        "\n",
        "#1.基礎參數設定與黑名單定義\n",
        "\n",
        "start_year, end_year = 2023, 2025\n",
        "download_dir = \"./binance_daily_zip\"\n",
        "os.makedirs(download_dir, exist_ok=True)\n",
        "\n",
        "HARD_BLACKLIST = {\n",
        "    'USDT', 'USDC', 'DAI', 'USDe', 'FDUSD', 'PYUSD', 'TUSD', 'BUSD',\n",
        "    'WBTC', 'STETH', 'WSTETH', 'CBETH', 'EETH', 'PUFETH', 'WBETH',\n",
        "    'LEO', 'OKB', 'KCS', 'HTX', 'GT', 'PAXG', 'XAUT', 'ONDO', 'W', 'AXL'\n",
        "}\n",
        "FUZZY_BLACKLIST = ['USD', 'EUR', 'GOLD', 'WRAP', 'BOND']\n",
        "\n",
        "\n",
        "#2.單線程獲取交易對\n",
        "\n",
        "exchange_info_url = \"https://fapi.binance.com/fapi/v1/exchangeInfo\"\n",
        "response = requests.get(exchange_info_url).json()\n",
        "\n",
        "all_usdt_symbols = []\n",
        "\n",
        "if 'symbols' not in response:\n",
        "    print(\"錯誤\")\n",
        "else:\n",
        "    all_usdt_symbols = [\n",
        "        market['symbol'] for market in response['symbols']\n",
        "        if market['quoteAsset'] == 'USDT' and market['contractType'] == 'PERPETUAL' and market['status'] == 'TRADING'\n",
        "    ]\n",
        "\n",
        "valid_symbols = []\n",
        "for symbol in all_usdt_symbols:\n",
        "    base_asset = symbol.replace('USDT', '')\n",
        "    if base_asset in HARD_BLACKLIST or any(kw in base_asset for kw in FUZZY_BLACKLIST):\n",
        "        continue\n",
        "    valid_symbols.append(symbol)\n",
        "\n",
        "print(f\"實際需要調研:{len(valid_symbols)}檔幣。\")\n",
        "\n",
        "\n",
        "#3.生成全量任務行事曆\n",
        "\n",
        "tasks = []\n",
        "if valid_symbols: # Only generate tasks if there are valid symbols\n",
        "    for symbol in valid_symbols:\n",
        "        for year in range(start_year, end_year + 1):\n",
        "            for month in range(1, 13):\n",
        "                file_name = f\"{symbol}-1d-{year}-{str(month).zfill(2)}\"\n",
        "                url = f\"https://data.binance.vision/data/futures/um/monthly/klines/{symbol}/1d/{file_name}.zip\"\n",
        "                tasks.append((symbol, file_name, url))\n",
        "\n",
        "\n",
        "#4.清洗函數\n",
        "\n",
        "def fetch_and_clean(task):\n",
        "    symbol, file_name, url = task\n",
        "    try:\n",
        "        res = requests.get(url, timeout=5)\n",
        "        if res.status_code == 200:\n",
        "            with zipfile.ZipFile(io.BytesIO(res.content)) as z:\n",
        "                csv_name = f\"{file_name}.csv\"\n",
        "                if csv_name in z.namelist():\n",
        "                    df = pd.read_csv(z.open(csv_name), header=None)\n",
        "                    df = df[df[0] != 'open_time']\n",
        "                    df = df[[0, 1, 4, 5]]\n",
        "                    df.columns = ['timestamp', 'open', 'close', 'volume']\n",
        "\n",
        "                    df['timestamp'] = pd.to_numeric(df['timestamp'], errors='coerce')\n",
        "                    df['open'] = pd.to_numeric(df['open'], errors='coerce')\n",
        "                    df['close'] = pd.to_numeric(df['close'], errors='coerce')\n",
        "                    df['volume'] = pd.to_numeric(df['volume'], errors='coerce')\n",
        "                    df = df.dropna()\n",
        "\n",
        "                    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')\n",
        "                    df['daily_turnover'] = ((df['open'] + df['close']) / 2) * df['volume']\n",
        "                    df['symbol'] = symbol\n",
        "                    return df[['timestamp', 'symbol', 'daily_turnover']]\n",
        "    except:\n",
        "        pass\n",
        "    return None\n",
        "\n",
        "\n",
        "#5.下載與清洗\n",
        "# ==============================================================================\n",
        "all_dfs = []\n",
        "\n",
        "if tasks: # Only proceed if there are tasks to execute\n",
        "    with ThreadPoolExecutor(max_workers=20) as executor:\n",
        "        futures = [executor.submit(fetch_and_clean, task) for task in tasks]\n",
        "        for future in tqdm(futures, desc=\"清洗中\"):\n",
        "            res_df = future.result()\n",
        "            if res_df is not None and not res_df.empty:\n",
        "                all_dfs.append(res_df)\n",
        "\n",
        "if all_dfs: # Only concatenate if there are dataframes to concatenate\n",
        "    full_daily_df = pd.concat(all_dfs, ignore_index=True)\n",
        "\n",
        "\n",
        "    #6.每週滾動樣本池矩陣運算\n",
        "\n",
        "    turnover_matrix = full_daily_df.pivot(index='timestamp', columns='symbol', values='daily_turnover').fillna(0)\n",
        "\n",
        "    current_monday = turnover_matrix.index.min() + timedelta(days=(0 - turnover_matrix.index.min().weekday()) % 7)\n",
        "    end_date = turnover_matrix.index.max()\n",
        "\n",
        "    universe_history = {}\n",
        "    global_universe_set = set()\n",
        "\n",
        "    while current_monday <= end_date:\n",
        "        if current_monday >= datetime(2026, 1, 1):\n",
        "            break\n",
        "        last_week_turnover = turnover_matrix.loc[current_monday - timedelta(days=7) : current_monday - timedelta(days=1)]\n",
        "        if not last_week_turnover.empty:\n",
        "            top_20 = last_week_turnover.mean(axis=0).sort_values(ascending=False).head(20).index.tolist()\n",
        "            universe_history[current_monday.strftime('%Y-W%W')] = top_20\n",
        "            global_universe_set.update(top_20)\n",
        "        current_monday += timedelta(days=7)\n",
        "\n",
        "    with open('universe_history.json', 'w') as f:\n",
        "        json.dump(universe_history, f, indent=4)\n",
        "\n",
        "    global_universe_list = list(global_universe_set)\n",
        "    print(f\"2. 總聯集池幣種數量:{len(global_universe_list)}\")\n",
        "    print(global_universe_list)\n",
        "else: # Corrected from elso\n",
        "    print(\"無符合過濾條件的交易對\")\n",
        "    # Create an empty universe_history.json if no data was processed to avoid FileNotFoundError in subsequent cells\n",
        "    with open('universe_history.json', 'w') as f:\n",
        "        json.dump({}, f, indent=4)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "uKMir_F5LoVY",
        "outputId": "cfe06db0-0909-4fdb-c687-b440e409b861",
        "collapsed": true
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "🔍 正在獲取幣安所有 U 本位永續合約交易對...\n",
            "❌ 錯誤：無法從幣安 API 獲取交易對資訊。API 回應: {'code': 0, 'msg': \"Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error.\"}\n",
            "這通常是因為您所在的地區無法訪問幣安 API，或者存在網路問題。請檢查您的網路或嘗試使用 VPN。\n",
            "✅ 核心池過濾完畢，實際需要調研: 0 檔幣。\n",
            "⚡ 啟動 20 執行緒雲端並行流式清洗中...\n",
            "\n",
            "⚠️ 無法獲取幣安交易對資料，或者沒有符合過濾條件的交易對。跳過後續數據處理。\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import json\n",
        "import requests\n",
        "from concurrent.futures import ThreadPoolExecutor, as_completed\n",
        "from tqdm.notebook import tqdm\n",
        "\n",
        "#1.建立5m高頻資料夾\n",
        "save_dir = \".binance_futures_5m_zips\"\n",
        "os.makedirs(save_dir, exist_ok=True)\n",
        "\n",
        "#讀取上階段的JSON檔\n",
        "json_path = '/content/drive/MyDrive/universe_history.json'\n",
        "if not os.path.exists(json_path):\n",
        "    raise FileNotFoundError(f\"❌ 找不到 {json_path}，請確認第一階段是否成功跑完並產出檔案。\")\n",
        "\n",
        "with open(json_path, 'r') as f:\n",
        "    universe_history = json.load(f)\n",
        "\n",
        "#提取出所有出現過的幣種\n",
        "symbols = set()\n",
        "for week, symbol_list in universe_history.items():\n",
        "    symbols.update(symbol_list)\n",
        "symbols = list(symbols)\n",
        "\n",
        "print(f\"Universe共包含{len(symbols)}檔幣\")\n",
        "\n",
        "\n",
        "#3.預先生成下載\n",
        "download_tasks = []\n",
        "for symbol in symbols:\n",
        "    for year in [2023, 2024, 2025]:\n",
        "        for month in range(1, 13):\n",
        "            file_name = f\"{symbol}-5m-{year}-{str(month).zfill(2)}.zip\"\n",
        "            url = f\"https://data.binance.vision/data/futures/um/monthly/klines/{symbol}/5m/{file_name}\"\n",
        "            local_path = os.path.join(save_dir, file_name)\n",
        "            download_tasks.append((url, local_path))\n",
        "\n",
        "print(f\"生成{len(download_tasks)}個下載任務\")\n",
        "\n",
        "\n",
        "#4.執行緒下載函數\n",
        "def download_single_file(task):\n",
        "    url, local_path = task\n",
        "    if os.path.exists(local_path):\n",
        "        return True\n",
        "    try:\n",
        "        res = requests.get(url, timeout=5)\n",
        "        if res.status_code == 200:\n",
        "            with open(local_path, \"wb\") as f:\n",
        "                f.write(res.content)\n",
        "            return True\n",
        "    except:\n",
        "        pass\n",
        "    return False\n",
        "\n",
        "#5.開跑\n",
        "success_count = 0\n",
        "with ThreadPoolExecutor(max_workers=20) as executor:\n",
        "    futures = {executor.submit(download_single_file, task): task for task in download_tasks}\n",
        "    for future in tqdm(as_completed(futures), total=len(futures), desc=\"下載中\"):\n",
        "        if future.result():\n",
        "            success_count += 1\n",
        "\n",
        "print(f\"下載了{success_count}個數據\")\n",
        "print(f\"存放在Colab虛擬機的`{save_dir}`\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 198,
          "referenced_widgets": [
            "646982e4bc3940948a9173a9d5c191ff",
            "12908979c4a549c1805d72d5996005a9",
            "4a84e2354bdb41fa807f2cd7f699e349",
            "484663feb2ba436c8f904a80f1bcd4e5",
            "fea681a112374c14aea9d773001d8d1f",
            "4292bd98ee3745da8dfc5cc2fdfb2dd9",
            "582518aa760d4f89a682975bff5d241a",
            "41d9fd074aae4adf9458885f6c661af3",
            "2d5d8103e0614d2ca984907001faf827",
            "5352a5cc8bb444ed95e278bfcdff3296",
            "6465569438a94f8a97812e9100995c64"
          ]
        },
        "id": "bX4jZcNHNOjw",
        "outputId": "01e5299c-c09b-4277-cc70-8313a23ca310"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "✅ 成功自動讀取 JSON！歷史動態 Universe 總共包含 267 檔獨特幣種。\n",
            "📅 總計生成 9612 個 5min 高頻數據下載任務。\n",
            "⚡ 正在啟動 Google 雲端 20 執行緒並行下載...\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "🚀 5m 高頻多執行緒下載中:   0%|          | 0/9612 [00:00<?, ?it/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "646982e4bc3940948a9173a9d5c191ff"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "🏆 【第二階段·高頻下載完美收工】\n",
            "✅ 成功精準下載了 5875 個高頻數據月份包！\n",
            "📁 檔案存放在 Colab 虛擬機的 `./binance_5m_zips` 資料夾中。\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import json\n",
        "import requests\n",
        "from concurrent.futures import ThreadPoolExecutor, as_completed\n",
        "from tqdm.notebook import tqdm\n",
        "\n",
        "#1.建立現貨5m雲端暫存資料夾\n",
        "spot_dir = \"/content/binance_spot_5m_zips\"\n",
        "os.makedirs(spot_dir, exist_ok=True)\n",
        "\n",
        "json_path = '/content/drive/MyDrive/universe_history.json'\n",
        "if not os.path.exists(json_path):\n",
        "    raise FileNotFoundError(f\"錯誤\")\n",
        "\n",
        "with open(json_path, 'r') as f:\n",
        "    universe_history = json.load(f)\n",
        "\n",
        "#聯集池幣種\n",
        "symbols = set()\n",
        "for week, symbol_list in universe_history.items():\n",
        "    symbols.update(symbol_list)\n",
        "symbols = list(symbols)\n",
        "\n",
        "print(f\"共包含{len(symbols)}檔幣種。\")\n",
        "\n",
        "\n",
        "#2.全量現貨下載\n",
        "download_tasks = []\n",
        "for symbol in symbols:\n",
        "    for year in [2023, 2024, 2025]:\n",
        "        for month in range(1, 13):\n",
        "            file_name = f\"{symbol}-5m-{year}-{str(month).zfill(2)}.zip\"\n",
        "            url = f\"https://data.binance.vision/data/spot/monthly/klines/{symbol}/5m/{file_name}\"\n",
        "            local_path = os.path.join(spot_dir, file_name)\n",
        "            download_tasks.append((url, local_path))\n",
        "\n",
        "print(f\"總生成{len(download_tasks)}個現貨5m數據\")\n",
        "\n",
        "# 3. 核心多執行緒下載函數\n",
        "def download_spot_file(task):\n",
        "    url, local_path = task\n",
        "    if os.path.exists(local_path):\n",
        "        return True\n",
        "    try:\n",
        "\n",
        "        res = requests.get(url, timeout=5)\n",
        "        if res.status_code == 200:\n",
        "            with open(local_path, \"wb\") as f:\n",
        "                f.write(res.content)\n",
        "            return True\n",
        "        elif res.status_code == 404:\n",
        "            return False\n",
        "    except Exception:\n",
        "        return False\n",
        "\n",
        "\n",
        "#4.開跑\n",
        "\n",
        "success_count = 0\n",
        "with ThreadPoolExecutor(max_workers=20) as executor:\n",
        "\n",
        "    futures = {executor.submit(download_spot_file, task): task for task in download_tasks}\n",
        "\n",
        "\n",
        "    for future in tqdm(as_completed(futures), total=len(futures), desc=\"下載中\"):\n",
        "        if future.result():\n",
        "            success_count += 1\n",
        "\n",
        "print(f\"下載了{success_count}個現貨\")\n",
        "print(f\"檔案在Colab虛擬機的`{spot_dir}` 資料夾\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 198,
          "referenced_widgets": [
            "3f2c15b8a04e4ae0b2d730e9260bd4e3",
            "0b223a6d40664f21bc4b8f7607871241",
            "d7802e0b4f074096b2061653ada506c7",
            "6811b7c53bd84741aa6a7df179bd8b90",
            "b19569495c4a457682f20f5aa3faf73c",
            "1cca3c626d094dc19f3c1e3af075daf6",
            "031e14fc737047c39bc636461c558e1f",
            "0cedcfda80ed49759e657e6acb781e37",
            "cbba6a0722694e13a04a4805bf4dee88",
            "30e00240dcfd4598878dff109c47827a",
            "984500550aa84f92bc18dca48935001f"
          ]
        },
        "id": "P7NvzdEFZEgM",
        "outputId": "b9ebf3ed-6062-4477-f3f2-0f059eb8b730",
        "collapsed": true
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "📦 歷史動態 Universe 總共包含 267 檔獨特核心幣種。\n",
            "📅 總計生成 9612 個【現貨 Spot】5m 高頻數據下載任務。\n",
            "⚡ 正在啟動 Google 雲端 20 執行緒並行暴力下載...\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "📥 現貨 5m 高頻下載中:   0%|          | 0/9612 [00:00<?, ?it/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "3f2c15b8a04e4ae0b2d730e9260bd4e3"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "🏆 【第二階段·現貨下載完美收工】\n",
            "✅ 成功精準下載了 5451 個【現貨】高頻數據月份包！\n",
            "📁 檔案已全部安全躺在 Colab 虛擬機的 `/content/binance_spot_5m_zips` 資料夾中。\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import zipfile\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import warnings\n",
        "from datetime import datetime, timedelta\n",
        "from tqdm.notebook import tqdm\n",
        "from collections import defaultdict\n",
        "\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "\n",
        "#1.初始化資料夾路徑\n",
        "futures_dir = \"/content/binance_futures_5m_zips\"\n",
        "spot_dir = \"./binance_spot_5m_zips\"\n",
        "output_dir = \"./alpha_features\"\n",
        "os.makedirs(output_dir, exist_ok=True)\n",
        "\n",
        "#掃描期現所有ZIP\n",
        "f_files = [f for f in os.listdir(futures_dir) if f.endswith('.zip')]\n",
        "s_files = [f for f in os.listdir(spot_dir) if f.endswith('.zip')]\n",
        "\n",
        "#幣種->月份檔案\n",
        "futures_map = defaultdict(list)\n",
        "for f in f_files:\n",
        "    symbol = f.split('-')[0]\n",
        "    futures_map[symbol].append(f)\n",
        "\n",
        "sport_map = defaultdict(list)\n",
        "for f in s_files:\n",
        "    symbol = f.split('-')[0]\n",
        "    sport_map[symbol].append(f)\n",
        "\n",
        "#找出期貨與現貨同時存在的交集幣\n",
        "valid_symbols = list(set(futures_map.keys()) & set(sport_map.keys()))\n",
        "print(f\"共{len(valid_symbols)}檔幣進入6大Alpha因子矩陣\")\n",
        "\n",
        "\n",
        "#2.5m微觀聚合->8H降頻\n",
        "def process_symbol_features(symbol):\n",
        "    #讀取並合併期貨3年5m數據\n",
        "    f_month_dfs = []\n",
        "    for f_file in futures_map[symbol]:\n",
        "        try:\n",
        "            with zipfile.ZipFile(os.path.join(futures_dir, f_file), 'r') as z:\n",
        "                csv = f_file.replace('.zip', '.csv')\n",
        "                df = pd.read_csv(z.open(csv), header=None, usecols=[0, 4, 5])\n",
        "                df.columns = ['timestamp', 'f_close', 'f_volume']\n",
        "                df = df[df['timestamp'] != 'open_time']\n",
        "                f_month_dfs.append(df)\n",
        "        except: pass\n",
        "\n",
        "    #讀取並合併現貨3年5m數據\n",
        "    s_month_dfs = []\n",
        "    for s_file in sport_map[symbol]:\n",
        "        try:\n",
        "            with zipfile.ZipFile(os.path.join(spot_dir, s_file), 'r') as z:\n",
        "                csv = s_file.replace('.zip', '.csv')\n",
        "                df = pd.read_csv(z.open(csv), header=None, usecols=[0, 4])\n",
        "                df.columns = ['timestamp', 's_close']\n",
        "                df = df[df['timestamp'] != 'open_time']\n",
        "                s_month_dfs.append(df)\n",
        "        except: pass\n",
        "\n",
        "    if not f_month_dfs or not s_month_dfs: return None\n",
        "\n",
        "    f_df = pd.concat(f_month_dfs, ignore_index=True)\n",
        "    s_df = pd.concat(s_month_dfs, ignore_index=True)\n",
        "\n",
        "    for df_raw in [f_df, s_df]: # Renamed loop variable to avoid confusion\n",
        "        for col in df_raw.columns:\n",
        "            df_raw[col] = pd.to_numeric(df_raw[col], errors='coerce')\n",
        "\n",
        "        df_raw['timestamp'] = pd.to_datetime(df_raw['timestamp'], unit='ms', errors='coerce')\n",
        "        df_raw.dropna(subset=['timestamp'], inplace=True)\n",
        "\n",
        "        df_raw = df_raw[(df_raw['timestamp'] >= '2023-01-01') & (df_raw['timestamp'] <= '2026-01-01')]\n",
        "\n",
        "    f_df = f_df.set_index('timestamp').sort_index()\n",
        "    s_df = s_df.set_index('timestamp').sort_index()\n",
        "\n",
        "\n",
        "    merged_5m = pd.merge_asof(\n",
        "        f_df.reset_index(),\n",
        "        s_df.reset_index(),\n",
        "        on='timestamp',\n",
        "        direction='nearest',\n",
        "        tolerance=pd.Timedelta('15s')\n",
        "    ).set_index('timestamp')\n",
        "    if merged_5m.empty: return None\n",
        "\n",
        "    merged_5m['f_return'] = merged_5m['f_close'].pct_change().abs()\n",
        "    merged_5m['basis_5m'] = (merged_5m['f_close'] - merged_5m['s_close']) / merged_5m['s_close']\n",
        "    merged_5m['amihud_raw'] = np.where(merged_5m['f_volume'] > 0, merged_5m['f_return'] / merged_5m['f_volume'], 0)\n",
        "\n",
        "    #降頻聚合\n",
        "    resampled_8h = pd.DataFrame(index=merged_5m['f_close'].resample('8h').last().index)\n",
        "    resampled_8h['f1_basis'] = merged_5m['basis_5m'].resample('8h').last()\n",
        "    resampled_8h['f2_delta_basis'] = resampled_8h['f1_basis'].diff()\n",
        "    resampled_8h['f3_basis_std'] = merged_5m['basis_5m'].resample('8h').std()\n",
        "\n",
        "    def calc_corr(window):\n",
        "        if len(window) < 10: return np.nan\n",
        "        return window['f_close'].corr(window['s_close'])\n",
        "    resampled_8h['f4_price_corr'] = merged_5m[['f_close', 's_close']].resample('8h').apply(calc_corr)\n",
        "    resampled_8h['f6_illiquidity'] = merged_5m['amihud_raw'].resample('8h').mean()\n",
        "\n",
        "    rolling_mean = resampled_8h['f1_basis'].rolling(window=21, min_periods=5).mean()\n",
        "    rolling_std = resampled_8h['f1_basis'].rolling(window=21, min_periods=5).std()\n",
        "    resampled_8h['f5_basis_zscore'] = np.where(rolling_std > 0, (resampled_8h['f1_basis'] - rolling_mean) / rolling_std, 0)\n",
        "\n",
        "    resampled_8h = resampled_8h.ffill().fillna(0)\n",
        "    resampled_8h['symbol'] = symbol\n",
        "    return resampled_8h.reset_index()\n",
        "\n",
        "\n",
        "# 3. 執行流式運算\n",
        "all_symbol_features = []\n",
        "for symbol in tqdm(valid_symbols, desc=\"洗煉中\"):\n",
        "    res = process_symbol_features(symbol)\n",
        "    if res is not None:\n",
        "        all_symbol_features.append(res)\n",
        "\n",
        "full_feature_df = pd.concat(all_symbol_features, ignore_index=True)\n",
        "full_feature_df = full_feature_df[(full_feature_df['timestamp'] >= '2023-01-01') & (full_feature_df['timestamp'] <= '2025-12-31')]\n",
        "\n",
        "factor_names = {\n",
        "    'f1_basis': 'basis_absolute.csv',\n",
        "    'f2_delta_basis': 'basis_speed.csv',\n",
        "    'f3_basis_std': 'basis_micro_vol.csv',\n",
        "    'f4_price_corr': 'price_micro_corr.csv',\n",
        "    'f5_basis_zscore': 'basis_zscore_7d.csv',\n",
        "    'f6_illiquidity': 'futures_illiquidity.csv'\n",
        "}\n",
        "\n",
        "for field, file_name in factor_names.items():\n",
        "    matrix = full_feature_df.pivot(index='timestamp', columns='symbol', values=field)\n",
        "    matrix = matrix.ffill().fillna(0)\n",
        "    matrix.to_csv(os.path.join(output_dir, file_name))\n",
        "    print(f\"因子矩陣表->{file_name}|維度:{matrix.shape}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 233,
          "referenced_widgets": [
            "2a4cfc3240f6488ab218022cd5ec30c5",
            "cd63b087e7044a3ca8080322f6a9578b",
            "db2b47366e4742b88fffecf999c03159",
            "b8debe7a964e4ffdbf1854d5549ec947",
            "8c04f105fc7a4d82b56470c7820a7966",
            "47582ca776cf4687b5cbd74880e0e4aa",
            "0bd0fd41c4324307ab8bcab594d520e6",
            "3a4022ea199b44abb4e3067eeffc0d17",
            "e46edcd6847d424b8c6f41922da946d0",
            "d383f59a2ac74129892bf57c695385e3",
            "f42b23e4da27494197c9ae1dfa4cbdae"
          ]
        },
        "id": "ZbV821v6bzdc",
        "outputId": "915b14e3-38a8-46d8-e42a-c21b9361d73f"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "🧱 雙邊數據對齊完畢，共 216 檔核心幣種進入 6 大 Alpha 因子淬煉矩陣...\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "🧱 6大 Alpha 因子流式洗煉中:   0%|          | 0/216 [00:00<?, ?it/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "2a4cfc3240f6488ab218022cd5ec30c5"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "💾 已導出因子矩陣表 -> basis_absolute.csv | 維度: (3286, 216)\n",
            "💾 已導出因子矩陣表 -> basis_speed.csv | 維度: (3286, 216)\n",
            "💾 已導出因子矩陣表 -> basis_micro_vol.csv | 維度: (3286, 216)\n",
            "💾 已導出因子矩陣表 -> price_micro_corr.csv | 維度: (3286, 216)\n",
            "💾 已導出因子矩陣表 -> basis_zscore_7d.csv | 維度: (3286, 216)\n",
            "💾 已導出因子矩陣表 -> futures_illiquidity.csv | 維度: (3286, 216)\n",
            "\n",
            "🏆 【第三階段·黃金特徵矩陣工程全數完美收工！】\n"
          ]
        }
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "widgets": {
      "application/vnd.jupyter.widget-state+json": {
        "version_major": 2,
        "version_minor": 0,
        "state": {
          "646982e4bc3940948a9173a9d5c191ff": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "HBoxModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "HBoxModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "HBoxView",
              "box_style": "",
              "children": [
                "IPY_MODEL_12908979c4a549c1805d72d5996005a9",
                "IPY_MODEL_4a84e2354bdb41fa807f2cd7f699e349",
                "IPY_MODEL_484663feb2ba436c8f904a80f1bcd4e5"
              ],
              "layout": "IPY_MODEL_fea681a112374c14aea9d773001d8d1f"
            }
          },
          "12908979c4a549c1805d72d5996005a9": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "HTMLModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "HTMLModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "HTMLView",
              "description": "",
              "description_tooltip": null,
              "layout": "IPY_MODEL_4292bd98ee3745da8dfc5cc2fdfb2dd9",
              "placeholder": "​",
              "style": "IPY_MODEL_582518aa760d4f89a682975bff5d241a",
              "value": "🚀 5m 高頻多執行緒下載中: 100%"
            }
          },
          "4a84e2354bdb41fa807f2cd7f699e349": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "FloatProgressModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "FloatProgressModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "ProgressView",
              "bar_style": "success",
              "description": "",
              "description_tooltip": null,
              "layout": "IPY_MODEL_41d9fd074aae4adf9458885f6c661af3",
              "max": 9612,
              "min": 0,
              "orientation": "horizontal",
              "style": "IPY_MODEL_2d5d8103e0614d2ca984907001faf827",
              "value": 9612
            }
          },
          "484663feb2ba436c8f904a80f1bcd4e5": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "HTMLModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "HTMLModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "HTMLView",
              "description": "",
              "description_tooltip": null,
              "layout": "IPY_MODEL_5352a5cc8bb444ed95e278bfcdff3296",
              "placeholder": "​",
              "style": "IPY_MODEL_6465569438a94f8a97812e9100995c64",
              "value": " 9612/9612 [03:43&lt;00:00, 22.04it/s]"
            }
          },
          "fea681a112374c14aea9d773001d8d1f": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "4292bd98ee3745da8dfc5cc2fdfb2dd9": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "582518aa760d4f89a682975bff5d241a": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          },
          "41d9fd074aae4adf9458885f6c661af3": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "2d5d8103e0614d2ca984907001faf827": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "ProgressStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "ProgressStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "bar_color": null,
              "description_width": ""
            }
          },
          "5352a5cc8bb444ed95e278bfcdff3296": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "6465569438a94f8a97812e9100995c64": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          },
          "3f2c15b8a04e4ae0b2d730e9260bd4e3": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "HBoxModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "HBoxModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "HBoxView",
              "box_style": "",
              "children": [
                "IPY_MODEL_0b223a6d40664f21bc4b8f7607871241",
                "IPY_MODEL_d7802e0b4f074096b2061653ada506c7",
                "IPY_MODEL_6811b7c53bd84741aa6a7df179bd8b90"
              ],
              "layout": "IPY_MODEL_b19569495c4a457682f20f5aa3faf73c"
            }
          },
          "0b223a6d40664f21bc4b8f7607871241": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "HTMLModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "HTMLModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "HTMLView",
              "description": "",
              "description_tooltip": null,
              "layout": "IPY_MODEL_1cca3c626d094dc19f3c1e3af075daf6",
              "placeholder": "​",
              "style": "IPY_MODEL_031e14fc737047c39bc636461c558e1f",
              "value": "📥 現貨 5m 高頻下載中: 100%"
            }
          },
          "d7802e0b4f074096b2061653ada506c7": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "FloatProgressModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "FloatProgressModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "ProgressView",
              "bar_style": "success",
              "description": "",
              "description_tooltip": null,
              "layout": "IPY_MODEL_0cedcfda80ed49759e657e6acb781e37",
              "max": 9612,
              "min": 0,
              "orientation": "horizontal",
              "style": "IPY_MODEL_cbba6a0722694e13a04a4805bf4dee88",
              "value": 9612
            }
          },
          "6811b7c53bd84741aa6a7df179bd8b90": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "HTMLModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "HTMLModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "HTMLView",
              "description": "",
              "description_tooltip": null,
              "layout": "IPY_MODEL_30e00240dcfd4598878dff109c47827a",
              "placeholder": "​",
              "style": "IPY_MODEL_984500550aa84f92bc18dca48935001f",
              "value": " 9612/9612 [03:35&lt;00:00, 26.16it/s]"
            }
          },
          "b19569495c4a457682f20f5aa3faf73c": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "1cca3c626d094dc19f3c1e3af075daf6": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "031e14fc737047c39bc636461c558e1f": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          },
          "0cedcfda80ed49759e657e6acb781e37": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "cbba6a0722694e13a04a4805bf4dee88": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "ProgressStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "ProgressStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "bar_color": null,
              "description_width": ""
            }
          },
          "30e00240dcfd4598878dff109c47827a": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "984500550aa84f92bc18dca48935001f": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          },
          "2a4cfc3240f6488ab218022cd5ec30c5": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "HBoxModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "HBoxModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "HBoxView",
              "box_style": "",
              "children": [
                "IPY_MODEL_cd63b087e7044a3ca8080322f6a9578b",
                "IPY_MODEL_db2b47366e4742b88fffecf999c03159",
                "IPY_MODEL_b8debe7a964e4ffdbf1854d5549ec947"
              ],
              "layout": "IPY_MODEL_8c04f105fc7a4d82b56470c7820a7966"
            }
          },
          "cd63b087e7044a3ca8080322f6a9578b": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "HTMLModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "HTMLModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "HTMLView",
              "description": "",
              "description_tooltip": null,
              "layout": "IPY_MODEL_47582ca776cf4687b5cbd74880e0e4aa",
              "placeholder": "​",
              "style": "IPY_MODEL_0bd0fd41c4324307ab8bcab594d520e6",
              "value": "🧱 6大 Alpha 因子流式洗煉中: 100%"
            }
          },
          "db2b47366e4742b88fffecf999c03159": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "FloatProgressModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "FloatProgressModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "ProgressView",
              "bar_style": "success",
              "description": "",
              "description_tooltip": null,
              "layout": "IPY_MODEL_3a4022ea199b44abb4e3067eeffc0d17",
              "max": 216,
              "min": 0,
              "orientation": "horizontal",
              "style": "IPY_MODEL_e46edcd6847d424b8c6f41922da946d0",
              "value": 216
            }
          },
          "b8debe7a964e4ffdbf1854d5549ec947": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "HTMLModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "HTMLModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "HTMLView",
              "description": "",
              "description_tooltip": null,
              "layout": "IPY_MODEL_d383f59a2ac74129892bf57c695385e3",
              "placeholder": "​",
              "style": "IPY_MODEL_f42b23e4da27494197c9ae1dfa4cbdae",
              "value": " 216/216 [09:22&lt;00:00,  2.65s/it]"
            }
          },
          "8c04f105fc7a4d82b56470c7820a7966": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "47582ca776cf4687b5cbd74880e0e4aa": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "0bd0fd41c4324307ab8bcab594d520e6": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          },
          "3a4022ea199b44abb4e3067eeffc0d17": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "e46edcd6847d424b8c6f41922da946d0": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "ProgressStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "ProgressStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "bar_color": null,
              "description_width": ""
            }
          },
          "d383f59a2ac74129892bf57c695385e3": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "f42b23e4da27494197c9ae1dfa4cbdae": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          }
        }
      }
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}